"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const graphql_tag_1 = require("graphql-tag");
exports.gql = graphql_tag_1.default;
var Application_1 = require("./Application");
exports.Application = Application_1.Application;
var DataSource_1 = require("./DataSource");
exports.DataSource = DataSource_1.DataSource;
var Query_1 = require("./Query");
exports.Query = Query_1.Query;
var Mutation_1 = require("./Mutation");
exports.Mutation = Mutation_1.Mutation;
var Fragment_1 = require("./Fragment");
exports.Fragment = Fragment_1.Fragment;
